id: P000068
initial_creation_type: ebook
source_metadata:
  title: བློ་གྲོས་མཐའ་ཡས་པའི་མཛོད།
  authors:
  - མཛད་པ་པོ། དྭགས་པོ་བཀྲ་ཤིས་རྣམ་རྒྱལ།
  layers:
  - book_title
  - author
  - chapter_title
  - tsawa
  - quotation
  - sabche
  id: RDI-SS-21
web_metadata:
  title:
    en: Moonbeams of Mahamudra
    bo: ཕྱག་ཆེན་ཟླ་བའི་འོད་ཟེར།
  collection:
    en: RDI Study Series–  Book 21
    bo: ཐོས་བསམ་འཆད་ཉན་གྱི་རིམ་པ།–  དེབ། ༢༡
  author:
    en: Dakpo Tashi Namgyal
    bo: དྭགས་པོ་བཀྲ་ཤིས་རྣམ་རྒྱལ།
  pusblisher:
    en: Rigpe Dorje Institute
    bo: རིག་པའི་རྡོ་རྗེ་གཙུག་ལག་སློབ་ཉེར་ཁང་།
  sku: RDI-SS-21
  category:
    en: Mahamudra
    bo: ཕྱག་རྒྱ་ཆེན་པོ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: RDI-SS-21.epub
  description:
    en: ''
    bo: ''
